source "https://rubygems.org"

gem 'faker'
gem 'pry'
gem 'sqlite3', '~> 1.3.6'
gem "rake"
gem "database_cleaner"
gem 'activerecord', '~> 5.2.3', :require => 'active_record'
gem 'sinatra-activerecord'
gem 'require_all'
gem 'rack-cors'